FROM node:24-slim

WORKDIR /opt/app/

COPY bookinfo/src/ratings/package.json .

RUN npm install --omit=dev

WORKDIR /opt/microservices/

COPY bookinfo/src/ratings .

ENV APP_VERSION=v1
ENV NODE_PATH=/opt/app/node_modules

EXPOSE 9080

CMD ["node", "ratings.js", "9080"]
