FROM node:24-slim
WORKDIR /opt/microservices
COPY bookinfo/src/ratings/package.json .
RUN npm install --omit=dev
COPY bookinfo/src/ratings/ratings.js .
ENV APP_VERSION=v1
ENV NODE_PATH=/opt/microservices/node_modules
EXPOSE 9080
CMD ["node", "ratings.js", "9080"]
