FROM python3.9-slim

WORKDIR /app

COPY bookinfo/src/productpage/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY bookinfo/src/productpage/ .

CMD ["python", "productpage.py"]
